; DEBUG = 1
; INFO = 2
; WARNING = 3
; ERROR = 4

[log_levels]
DEFAULT=2

; uncomment these as needed, but probably copy this to config.local.ini (gitignored)
; and/or don't check in the change. debug output will never show up in the final build.

;AudioManager=1
;BirdFood=1
;BirdMonster=1
;CavernArea=1
;ClimbableTree=1
;Activator=1
;FishMonster=1
;FishPatrollingState=1
;GameManager=1
;GrabBox=1
;Plank=1
;Player=1
;Portal=1
;ShadowBlob=1
;StateMachine=1
;StateManager=1
;Teleplate=1
